INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Sucre', 'Oropeza', 'Chuquisaca', 10101);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Yotala', 'Oropeza', 'Chuquisaca', 10102);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Poroma', 'Oropeza', 'Chuquisaca', 10103);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Zudañez', 'Zudañez', 'Chuquisaca', 10301);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Icla (R.Mujia)', 'Zudañez', 'Chuquisaca', 10304);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Padilla', 'Tomina', 'Chuquisaca', 10401);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tomina', 'Tomina', 'Chuquisaca', 10402);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Monteagudo', 'Hernando Siles', 'Chuquisaca', 10501);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Pablo de Huacareta', 'Hernando Siles', 'Chuquisaca', 10502);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tarabuco', 'Yamparaez', 'Chuquisaca', 10601);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Yamparáez', 'Yamparaez', 'Chuquisaca', 10602);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Camargo', 'Nor Cinti', 'Chuquisaca', 10701);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Lucas', 'Nor Cinti', 'Chuquisaca', 10702);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Villa Charcas', 'Nor Cinti', 'Chuquisaca', 10704);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Villa Abecia', 'Sur Cinti', 'Chuquisaca', 10901);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Culpina', 'Sud Cinti', 'Chuquisaca', 10902);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Las Carretas', 'Sur Cinti', 'Chuquisaca', 10903);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Villa Vaca Guzmán (Muyupampa)', 'Luis Calvo', 'Chuquisaca', 11001);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Nuestra Señora de La Paz', 'Murillo', 'La Paz', 20101);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Palca', 'Murillo', 'La Paz', 20102);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Mecapaca', 'Murillo', 'La Paz', 20103);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Achocalla', 'Murillo', 'La Paz', 20104);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('El Alto', 'Murillo', 'La Paz', 20105);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Ancoraimes', 'Omasuyos', 'La Paz', 20202);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Chua Cocani', 'Omasuyos', 'La Paz', 20203);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Huarina', 'Omasuyos', 'La Paz', 20204);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Coro Coro', 'Pacajes', 'La Paz', 20301);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Caquiaviri', 'Pacajes', 'La Paz', 20302);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Calacoto', 'Pacajes', 'La Paz', 20303);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Comanche', 'Pacajes', 'La Paz', 20304);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Charaña', 'Pacajes', 'La Paz', 20305);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Santiago de Callapa', 'Pacajes', 'La Paz', 20308);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Puerto Acosta', 'Camacho', 'La Paz', 20401);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Mocomoco', 'Camacho', 'La Paz', 20402);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Puerto Carabuco', 'Camacho', 'La Paz', 20403);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Chuma', 'Muñecas', 'La Paz', 20501);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Ayata', 'Muñecas', 'La Paz', 20502);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Aucapata', 'Muñecas', 'La Paz', 20503);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Sorata', 'Larecaja', 'La Paz', 20601);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Guanay', 'Larecaja', 'La Paz', 20602);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tacacoma', 'Larecaja', 'La Paz', 20603);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Quiabaya', 'Larecaja', 'La Paz', 20604);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Combaya', 'Larecaja', 'La Paz', 20605);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tipuani', 'Larecaja', 'La Paz', 20606);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Mapiri', 'Larecaja', 'La Paz', 20607);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Teoponte', 'Larecaja', 'La Paz', 20608);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Apolo', 'Franz Tamayo', 'La Paz', 20701);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Pelechuco', 'Franz Tamayo', 'La Paz', 20702);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Viacha', 'Ingavi', 'La Paz', 20801);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tiahuanacu', 'Ingavi', 'La Paz', 20803);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Desaguadero', 'Ingavi', 'La Paz', 20804);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Andrés de Machaca', 'Ingavi', 'La Paz', 20805);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Jesús de Machaca', 'Ingavi', 'La Paz', 20806);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Luribay', 'Loayza', 'La Paz', 20901);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Sapahaqui', 'Loayza', 'La Paz', 20902);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Yaco', 'Loayza', 'La Paz', 20903);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Malla', 'Loayza', 'La Paz', 20904);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Cairoma', 'Loayza', 'La Paz', 20905);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Inquisivi', 'Inquisivi', 'La Paz', 21001);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Quime', 'Inquisivi', 'La Paz', 21002);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Cajuata', 'Inquisivi', 'La Paz', 21003);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Colquiri', 'Inquisivi', 'La Paz', 21004);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Ichoca', 'Inquisivi', 'La Paz', 21005);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Licoma (Villa Libertad)', 'Inquisivi', 'La Paz', 21006);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Chulumani', 'Sur Yungas', 'La Paz', 21101);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Irupana', 'Sur Yungas', 'La Paz', 21102);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Yanacachi', 'Sur Yungas', 'La Paz', 21103);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Palos Blancos', 'Sur Yungas', 'La Paz', 21104);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('La Asunta', 'Sur Yungas', 'La Paz', 21105);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Pucarani', 'Los Andes', 'La Paz', 21201);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Laja', 'Los Andes', 'La Paz', 21202);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Batallas', 'Los Andes', 'La Paz', 21203);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Puerto Perez', 'Los Andes', 'La Paz', 21204);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Sica Sica', 'Aroma', 'La Paz', 21301);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Ayo Ayo', 'Aroma', 'La Paz', 21303);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Calamarca', 'Aroma', 'La Paz', 21304);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Patacamaya', 'Aroma', 'La Paz', 21305);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Colquencha', 'Aroma', 'La Paz', 21306);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Collana', 'Aroma', 'La Paz', 21307);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Coroico', 'Nor Yungas', 'La Paz', 21401);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Coripata', 'Nor Yungas', 'La Paz', 21402);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Ixiamas', 'Abel Iturralde', 'La Paz', 21501);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Buenaventura', 'Abel Iturralde', 'La Paz', 21502);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Charazani (Gral.Perez)', 'Bautista Saavedra', 'La Paz', 21601);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Curva', 'Bautista Saavedra', 'La Paz', 21602);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Pedro de Curahuara', 'Gualberto Villarroe', 'La Paz', 21801);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Papel Pampa', 'Gualberto Villarroe', 'La Paz', 21802);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Chacarilla', 'Gualberto Villarroe', 'La Paz', 21803);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Santiago de Machaca', 'General Jose Manuel', 'La Paz', 21901);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Catacora', 'General Jose Manuel', 'La Paz', 21902);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Caranavi', 'Caranavi', 'La Paz', 22001);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Alto Beni', 'Caranavi', 'La Paz', 22002);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Cochabamba', 'Cercado', 'Cochabamba', 30101);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Aiquile', 'Campero', 'Cochabamba', 30201);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Pasorapa', 'Campero', 'Cochabamba', 30202);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Independencia', 'Ayopaya', 'Cochabamba', 30301);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Morochata', 'Ayopaya', 'Cochabamba', 30302);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Cocapata', 'Ayopaya', 'Cochabamba', 30303);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tarata', 'Esteban Arce', 'Cochabamba', 30401);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Anzaldo', 'Esteban Arce', 'Cochabamba', 30402);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Arbieto', 'Esteban Arce', 'Cochabamba', 30403);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Arani', 'Arani', 'Cochabamba', 30501);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Vacas', 'Arani', 'Cochabamba', 30502);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Arque', 'Arque', 'Cochabamba', 30601);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tacopaya', 'Arque', 'Cochabamba', 30602);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Capinota', 'Capinota', 'Cochabamba', 30701);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Santibañez', 'Capinota', 'Cochabamba', 30702);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Sicaya', 'Capinota', 'Cochabamba', 30703);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Toko', 'German Jordan', 'Cochabamba', 30802);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Quillacollo', 'Quillacollo', 'Cochabamba', 30901);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Sipe Sipe', 'Quillacollo', 'Cochabamba', 30902);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Vinto', 'Quillacollo', 'Cochabamba', 30904);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Colcapirhua', 'Quillacollo', 'Cochabamba', 30905);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Sacaba', 'Chapare', 'Cochabamba', 31001);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Villa Tunari', 'Chapare', 'Cochabamba', 31003);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tapacarí', 'Tapacari', 'Cochabamba', 31101);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Puerto Villarroel', 'Carrasco', 'Cochabamba', 31205);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Entre Rios (Bulo Bulo)', 'Carrasco', 'Cochabamba', 31206);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Mizque', 'Mizque', 'Cochabamba', 31301);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Alalay', 'Mizque', 'Cochabamba', 31303);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Punata', 'Punata', 'Cochabamba', 31401);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Benito', 'Punata', 'Cochabamba', 31403);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Bolivar', 'Bolivar', 'Cochabamba', 31501);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tiraque', 'Tiraque', 'Cochabamba', 31601);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Oruro', 'Cercado', 'Oruro', 40101);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Caracollo', 'Cercado', 'Oruro', 40102);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('El Choro', 'Cercado', 'Oruro', 40103);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Paria', 'Cercado', 'Oruro', 40104);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Challapata', 'Abaroa', 'Oruro', 40201);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Santuario de Quillacas', 'Abaroa', 'Oruro', 40202);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Corque', 'Carangas', 'Oruro', 40301);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Turco', 'Sajama', 'Oruro', 40402);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Poopó', 'Poopo', 'Oruro', 40601);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Pazña', 'Poopo', 'Oruro', 40602);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Antequera (Bolivar)', 'Poopo', 'Oruro', 40603);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Villa Huanuni', 'Pantaleon Dalence', 'Oruro', 40701);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Machacamarca', 'Pantaleon Dalence', 'Oruro', 40702);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Salinas de Garci Mendoza', 'Ladislao Cabrera', 'Oruro', 40801);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Sabaya', 'Sabaya', 'Oruro', 40901);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Coipasa', 'Sabaya', 'Oruro', 40902);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Toledo', 'Saucari', 'Oruro', 41001);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('y', 'San Pedro De Totora', 'Oruro', 41301);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('La Rivera', 'Mejillones', 'Oruro', 41501);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Todos Santos', 'Mejillones', 'Oruro', 41502);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Carangas', 'Mejillones', 'Oruro', 41503);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Potosí', 'Tomas Frias', 'Potosi', 50101);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tinquipaya', 'Tomas Frias', 'Potosi', 50102);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Yocalla', 'Tomas Frias', 'Potosi', 50103);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Belén de Urmiri', 'Tomas Frias', 'Potosi', 50104);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Uncía', 'Rafael Bustillo', 'Potosi', 50201);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Chayanta', 'Rafael Bustillo', 'Potosi', 50202);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Llallagua', 'Rafael Bustillo', 'Potosi', 50203);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Chuquihuta', 'Rafael Bustillo', 'Potosi', 50204);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Betanzos', 'Cornelio Saavedra', 'Potosi', 50301);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Chaqui', 'Cornelio Saavedra', 'Potosi', 50302);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tacobamba', 'Cornelio Saavedra', 'Potosi', 50303);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Colquechaca', 'Chayanta', 'Potosi', 50401);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Ravelo', 'Chayanta', 'Potosi', 50402);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Pocoata', 'Chayanta', 'Potosi', 50403);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Ocuri', 'Chayanta', 'Potosi', 50404);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Pedro de Buena Vista', 'Charcas', 'Potosi', 50501);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Toro Toro', 'Charcas', 'Potosi', 50502);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Cotagaita', 'Nor Chichas', 'Potosi', 50601);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Vitichi', 'Nor Chichas', 'Potosi', 50602);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Sacaca', 'Alonso de Ibañez', 'Potosi', 50701);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Caripuyo', 'Alonso de Ibañez', 'Potosi', 50702);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tupiza', 'Sur Chichas', 'Potosi', 50801);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Atocha', 'Sur Chichas', 'Potosi', 50802);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Colcha"K" (V.Martin)', 'Nor Lipez', 'Potosi', 50901);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Pedro de Quemes', 'Nor Lipez', 'Potosi', 50902);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Pablo de Lipez', 'Sur Lipez', 'Potosi', 51001);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Mojinete', 'Sur Lipez', 'Potosi', 51002);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Antonio de Esmoraca', 'Sur Lipez', 'Potosi', 51003);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Puna', 'Jose Maria Linares', 'Potosi', 51101);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Caiza "D"', 'Jose Maria Linares', 'Potosi', 51102);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Ckochas', 'Jose Maria Linares', 'Potosi', 51103);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Uyuni (Thola Pampa)', 'Antonio Quijarro', 'Potosi', 51201);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tomave', 'Antonio Quijarro', 'Potosi', 51202);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Porco', 'Antonio Quijarro', 'Potosi', 51203);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Arampampa', 'General Bernardino', 'Potosi', 51301);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Acasio', 'General Bernardino', 'Potosi', 51302);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Llica', 'Daniel Campos', 'Potosi', 51401);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Villazón', 'Modesto Omiste', 'Potosi', 51501);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Agustín', 'Enrique Baldivieso', 'Potosi', 51601);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tarija', 'Cercado', 'Tarija', 60101);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Yacuiba', 'Gran Chaco', 'Tarija', 60301);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Caraparí', 'Gran Chaco', 'Tarija', 60302);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Yunchara', 'Avilez', 'Tarija', 60402);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Villa San Lorenzo', 'Mendez', 'Tarija', 60501);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Tomayapo (El Puente)', 'Mendez', 'Tarija', 60502);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Santa Cruz de la Sierra', 'Andres Ibañez', 'Santa Cruz', 70101);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Porongo (Ayacucho)', 'Andres Ibañez', 'Santa Cruz', 70103);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('La Guardia', 'Andres Ibañez', 'Santa Cruz', 70104);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('El Torno', 'Andres Ibañez', 'Santa Cruz', 70105);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Warnes', 'Warnes', 'Santa Cruz', 70201);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Ignacio de Velasco', 'Velasco', 'Santa Cruz', 70301);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Miguel de Velasco', 'Velasco', 'Santa Cruz', 70302);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Rafael', 'Velasco', 'Santa Cruz', 70303);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Buena Vista', 'Ichilo', 'Santa Cruz', 70401);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Carlos', 'Ichilo', 'Santa Cruz', 70402);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Yapacaní', 'Ichilo', 'Santa Cruz', 70403);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Jose de Chiquitos', 'Chiquitos', 'Santa Cruz', 70501);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Pailón', 'Chiquitos', 'Santa Cruz', 70502);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Robore', 'Chiquitos', 'Santa Cruz', 70503);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Santa Rosa del Sara', 'Sara', 'Santa Cruz', 70602);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Colpa Belgica', 'Sara', 'Santa Cruz', 70603);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Charagua', 'Cordillera', 'Santa Cruz', 70702);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Cabezas', 'Cordillera', 'Santa Cruz', 70703);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Gutiérrez', 'Cordillera', 'Santa Cruz', 70705);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Vallegrande', 'Valle Grande', 'Santa Cruz', 70801);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Samaipata', 'Florida', 'Santa Cruz', 70901);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Pampa Grande', 'Florida', 'Santa Cruz', 70902);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Concepción', 'Ñuflo De Chavez', 'Santa Cruz', 71101);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Javier', 'Ñuflo De Chavez', 'Santa Cruz', 71102);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Ramón', 'Ñuflo De Chavez', 'Santa Cruz', 71103);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Julián', 'Ñuflo De Chavez', 'Santa Cruz', 71104);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Antonio de Lomerio', 'Ñuflo De Chavez', 'Santa Cruz', 71105);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Matías', 'Angel Sandoval', 'Santa Cruz', 71201);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Comarapa', 'Manuel M. Caballero', 'Santa Cruz', 71301);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Puerto Suarez', 'German Busch', 'Santa Cruz', 71401);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Puerto Quijarro', 'German Busch', 'Santa Cruz', 71402);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Carmen Rivero Torrez', 'German Busch', 'Santa Cruz', 71403);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Ascención de Guarayos', 'Guarayos', 'Santa Cruz', 71501);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Urubicha', 'Guarayos', 'Santa Cruz', 71502);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('El Puente', 'Guarayos', 'Santa Cruz', 71503);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Riberalta', 'Vaca Diez', 'Beni', 80201);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Guayaramerín', 'Vaca Diez', 'Beni', 80202);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Reyes', 'General Jose Balliv', 'Beni', 80301);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Borja', 'General Jose Balliv', 'Beni', 80302);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Santa Rosa', 'General Jose Balliv', 'Beni', 80303);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Rurrenabaque', 'General Jose Balliv', 'Beni', 80304);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Exaltacion', 'Yacuma', 'Beni', 80402);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Ignacio', 'Moxos', 'Beni', 80501);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Joaquín', 'Mamore', 'Beni', 80701);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Magdalena', 'Itenez', 'Beni', 80801);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Baures', 'Itenez', 'Beni', 80802);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Porvenir', 'Nicolas Suarez', 'Pando', 90102);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Bella Flor', 'Nicolas Suarez', 'Pando', 90104);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Puerto Rico', 'Manuripi', 'Pando', 90201);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Pedro (Conquista)', 'Manuripi', 'Pando', 90202);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Filadelfia', 'Manuripi', 'Pando', 90203);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Puerto Gonzales Moreno', 'Madre De Dios', 'Pando', 90301);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('San Lorenzo', 'Madre De Dios', 'Pando', 90302);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('El Sena', 'Madre De Dios', 'Pando', 90303);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Santa Rosa del Abuná', 'Abuná', 'Pando', 90401);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Ingavi', 'Abuná', 'Pando', 90402);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Nuevo Manoa (Nueva Esperanza)', 'Federico Roman', 'Pando', 90501);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Villa Nueva (Loma Alta)', 'Federico Roman', 'Pando', 90502);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Entre Rios (La Moreta)', 'Burnet O''Connor', 'Tarija', 60601);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Choquecota', 'Carangas', 'Oruro', 40302);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Pampa Aullagas', 'Ladislao Cabrera', 'Oruro', 40802);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Eucaliptus', 'Tomas Barron', 'Oruro', 41101);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Santiago de Andamarca', 'Sur Carangas', 'Oruro', 41201);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Santiago de Huari', 'Sebastian Pagador', 'Oruro', 41401);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Santiago de Huayllamarca', 'Nor Carangas', 'Oruro', 41601);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Belen de Andamarca', 'Sur Carangas', 'Oruro', 41202);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Bermejo', 'Arce', 'Tarija', 60202);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Quirusillas', 'Florida', 'Santa Cruz', 70904);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Achacachi', 'Omasuyos', 'La Paz', 20201);
INSERT INTO "municipio" ("nombre", "provincia", "departamento", "codigo_municipio") VALUES ('Curahuara de Carangas', 'Sajama', 'Oruro', 40401);
