/*
Navicat PGSQL Data Transfer

Source Server         : postgres-vladi
Source Server Version : 90109
Source Host           : 192.168.78.160:5432
Source Database       : bdca
Source Schema         : public

Target Server Type    : PGSQL
Target Server Version : 90109
File Encoding         : 65001

Date: 2013-12-06 19:56:29
*/


-- ----------------------------
-- Table structure for "public"."t_boletaproductor_p1"
-- ----------------------------
DROP TABLE "public"."t_boletaproductor_p1";
CREATE TABLE "public"."t_boletaproductor_p1" (
"docid" varchar(20) NOT NULL,
"folio" varchar(6) NOT NULL,
"numerobrigada" varchar(4) NOT NULL,
"numeroempadronador" varchar(2) NOT NULL,
"numerosegmento" varchar(2) DEFAULT ''::character varying NOT NULL,
"numerohojacontrol" varchar(6) NOT NULL,
"codigodepartamento" varchar(2) NOT NULL,
"codigoprovincia" varchar(2) NOT NULL,
"codigomunicipio" varchar(2) NOT NULL,
"codigoareacensal" varchar(2) NOT NULL,
"codigocantoncensal" varchar(2) NOT NULL,
"tipoupa" varchar(2) NOT NULL,
"numeroorden" varchar(2) DEFAULT NULL::character varying,
"nombreespecifico" varchar(150) NOT NULL,
"nombrelocalidad" varchar(150) DEFAULT NULL::character varying,
"numerodistritomunicipal" varchar(2) DEFAULT NULL::character varying,
"p15_1" varchar(20) DEFAULT NULL::character varying,
"p15_2" varchar(20) DEFAULT NULL::character varying,
"p15_3" varchar(20) DEFAULT NULL::character varying,
"p15_4" varchar(20) DEFAULT NULL::character varying,
"p15_5" varchar(60) DEFAULT NULL::character varying,
"p16" int2,
"p17_1" varchar(40) DEFAULT NULL::character varying,
"p17_2" int2,
"p18" int2,
"p19" int2,
"p20_1" int2,
"p20_2" int2,
"p20_3" numeric(8,2) DEFAULT NULL::numeric,
"p20_4" varchar(2) DEFAULT NULL::character varying,
"p21_1_1" numeric(8,2) DEFAULT NULL::numeric,
"p21_1_2" varchar(2) DEFAULT NULL::character varying,
"p21_2_1" numeric(8,2) DEFAULT NULL::numeric,
"p21_2_2" varchar(2) DEFAULT NULL::character varying,
"p21_3_1" numeric(8,2) DEFAULT NULL::numeric,
"p21_3_2" varchar(2) DEFAULT NULL::character varying,
"p21_4_1" numeric(8,2) DEFAULT NULL::numeric,
"p21_4_2" varchar(2) DEFAULT NULL::character varying,
"p21_5_1" numeric(8,2) DEFAULT NULL::numeric,
"p21_5_2" varchar(2) DEFAULT NULL::character varying,
"p22_1" int2,
"p22_2" int2,
"p22_3" int2,
"p22_4" int2,
"p23_1" int2,
"p23_1_1" int2,
"p23_1_2" varchar(25) DEFAULT NULL::character varying,
"p23_1_3" numeric(8,2) DEFAULT NULL::numeric,
"p23_1_4" varchar(2) DEFAULT NULL::character varying,
"p23_1_5" int2,
"p23_1_6" varchar(2) DEFAULT NULL::character varying,
"p23_1_7" numeric(8,2) DEFAULT NULL::numeric,
"p23_1_8" varchar(2) DEFAULT NULL::character varying,
"p23_1_9" varchar(2) DEFAULT NULL::character varying,
"p23_1_10" int2,
"p23_1_11" int2,
"p23_1_12" int2,
"p23_2_1" int2,
"p23_2_2" varchar(25) DEFAULT NULL::character varying,
"p23_2_3" numeric(8,2) DEFAULT NULL::numeric,
"p23_2_4" varchar(2) DEFAULT NULL::character varying,
"p23_2_5" int2,
"p23_2_6" varchar(2) DEFAULT NULL::character varying,
"p23_2_7" numeric(8,2) DEFAULT NULL::numeric,
"p23_2_8" varchar(2) DEFAULT NULL::character varying,
"p23_2_9" varchar(2) DEFAULT NULL::character varying,
"p23_2_10" int2,
"p23_2_11" int2,
"p23_2_12" int2,
"p23_3_1" int2,
"p23_3_2" varchar(25) DEFAULT NULL::character varying,
"p23_3_3" numeric(8,2) DEFAULT NULL::numeric,
"p23_3_4" varchar(2) DEFAULT NULL::character varying,
"p23_3_5" int2,
"p23_3_6" varchar(2) DEFAULT NULL::character varying,
"p23_3_7" numeric(8,2) DEFAULT NULL::numeric,
"p23_3_8" varchar(2) DEFAULT NULL::character varying,
"p23_3_9" varchar(2) DEFAULT NULL::character varying,
"p23_3_10" int2,
"p23_3_11" int2,
"p23_3_12" int2,
"p23_4_1" int2,
"p23_4_2" varchar(25) DEFAULT NULL::character varying,
"p23_4_3" numeric(8,2) DEFAULT NULL::numeric,
"p23_4_4" varchar(2) DEFAULT NULL::character varying,
"p23_4_5" int2,
"p23_4_6" varchar(2) DEFAULT NULL::character varying,
"p23_4_7" numeric(8,2) DEFAULT NULL::numeric,
"p23_4_8" varchar(2) DEFAULT NULL::character varying,
"p23_4_9" varchar(2) DEFAULT NULL::character varying,
"p23_4_10" int2,
"p23_4_11" int2,
"p23_4_12" int2,
"p23_5_1" int2,
"p23_5_2" varchar(25) DEFAULT NULL::character varying,
"p23_5_3" numeric(8,2) DEFAULT NULL::numeric,
"p23_5_4" varchar(2) DEFAULT NULL::character varying,
"p23_5_5" int2,
"p23_5_6" varchar(2) DEFAULT NULL::character varying,
"p23_5_7" numeric(8,2) DEFAULT NULL::numeric,
"p23_5_8" varchar(2) DEFAULT NULL::character varying,
"p23_5_9" varchar(2) DEFAULT NULL::character varying,
"p23_5_10" int2,
"p23_5_11" int2,
"p23_5_12" int2,
"p23_6_1" int2,
"p23_6_2" varchar(25) DEFAULT NULL::character varying,
"p23_6_3" numeric(8,2) DEFAULT NULL::numeric,
"p23_6_4" varchar(2) DEFAULT NULL::character varying,
"p23_6_5" int2,
"p23_6_6" varchar(2) DEFAULT NULL::character varying,
"p23_6_7" numeric(8,2) DEFAULT NULL::numeric,
"p23_6_8" varchar(2) DEFAULT NULL::character varying,
"p23_6_9" varchar(2) DEFAULT NULL::character varying,
"p23_6_10" int2,
"p23_6_11" int2,
"p23_6_12" int2,
"p23_7_1" int2,
"p23_7_2" varchar(25) DEFAULT NULL::character varying,
"p23_7_3" numeric(8,2) DEFAULT NULL::numeric,
"p23_7_4" varchar(2) DEFAULT NULL::character varying,
"p23_7_5" int2,
"p23_7_6" varchar(2) DEFAULT NULL::character varying,
"p23_7_7" numeric(8,2) DEFAULT NULL::numeric,
"p23_7_8" varchar(2) DEFAULT NULL::character varying,
"p23_7_9" varchar(2) DEFAULT NULL::character varying,
"p23_7_10" int2,
"p23_7_11" int2,
"p23_7_12" int2,
"p24_1" int2,
"p24_1_1" int2,
"p24_1_2" varchar(20) DEFAULT NULL::character varying,
"p24_1_3" varchar(2) DEFAULT NULL::character varying,
"p24_1_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_1_5" varchar(2) DEFAULT NULL::character varying,
"p24_1_6" int2,
"p24_1_7" varchar(2) DEFAULT NULL::character varying,
"p24_1_8" int2,
"p24_1_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_1_10" varchar(2) DEFAULT NULL::character varying,
"p24_1_11" varchar(2) DEFAULT NULL::character varying,
"p24_1_12" int2,
"p24_1_13" int2,
"p24_1_14" int2,
"p24_2_1" int2,
"p24_2_2" varchar(20) DEFAULT NULL::character varying,
"p24_2_3" varchar(2) DEFAULT NULL::character varying,
"p24_2_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_2_5" varchar(2) DEFAULT NULL::character varying,
"p24_2_6" int2,
"p24_2_7" varchar(2) DEFAULT NULL::character varying,
"p24_2_8" int2,
"p24_2_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_2_10" varchar(2) DEFAULT NULL::character varying,
"p24_2_11" varchar(2) DEFAULT NULL::character varying,
"p24_2_12" int2,
"p24_2_13" int2,
"p24_2_14" int2,
"p24_3_1" int2,
"p24_3_2" varchar(20) DEFAULT NULL::character varying,
"p24_3_3" varchar(2) DEFAULT NULL::character varying,
"p24_3_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_3_5" varchar(2) DEFAULT NULL::character varying,
"p24_3_6" int2,
"p24_3_7" varchar(2) DEFAULT NULL::character varying,
"p24_3_8" int2,
"p24_3_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_3_10" varchar(2) DEFAULT NULL::character varying,
"p24_3_11" varchar(2) DEFAULT NULL::character varying,
"p24_3_12" int2,
"p24_3_13" int2,
"p24_3_14" int2,
"p24_4_1" int2,
"p24_4_2" varchar(20) DEFAULT NULL::character varying,
"p24_4_3" varchar(2) DEFAULT NULL::character varying,
"p24_4_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_4_5" varchar(2) DEFAULT NULL::character varying,
"p24_4_6" int2,
"p24_4_7" varchar(2) DEFAULT NULL::character varying,
"p24_4_8" int2,
"p24_4_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_4_10" varchar(2) DEFAULT NULL::character varying,
"p24_4_11" varchar(2) DEFAULT NULL::character varying,
"p24_4_12" int2,
"p24_4_13" int2,
"p24_4_14" int2,
"p24_5_1" int2,
"p24_5_2" varchar(20) DEFAULT NULL::character varying,
"p24_5_3" varchar(2) DEFAULT NULL::character varying,
"p24_5_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_5_5" varchar(2) DEFAULT NULL::character varying,
"p24_5_6" int2,
"p24_5_7" varchar(2) DEFAULT NULL::character varying,
"p24_5_8" int2,
"p24_5_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_5_10" varchar(2) DEFAULT NULL::character varying,
"p24_5_11" varchar(2) DEFAULT NULL::character varying,
"p24_5_12" int2,
"p24_5_13" int2,
"p24_5_14" int2,
"p24_6_1" int2,
"p24_6_2" varchar(20) DEFAULT NULL::character varying,
"p24_6_3" varchar(2) DEFAULT NULL::character varying,
"p24_6_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_6_5" varchar(2) DEFAULT NULL::character varying,
"p24_6_6" int2,
"p24_6_7" varchar(2) DEFAULT NULL::character varying,
"p24_6_8" int2,
"p24_6_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_6_10" varchar(2) DEFAULT NULL::character varying,
"p24_6_11" varchar(2) DEFAULT NULL::character varying,
"p24_6_12" int2,
"p24_6_13" int2,
"p24_6_14" int2,
"p24_7_1" int2,
"p24_7_2" varchar(20) DEFAULT NULL::character varying,
"p24_7_3" varchar(2) DEFAULT NULL::character varying,
"p24_7_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_7_5" varchar(2) DEFAULT NULL::character varying,
"p24_7_6" int2,
"p24_7_7" varchar(2) DEFAULT NULL::character varying,
"p24_7_8" int2,
"p24_7_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_7_10" varchar(2) DEFAULT NULL::character varying,
"p24_7_11" varchar(2) DEFAULT NULL::character varying,
"p24_7_12" int2,
"p24_7_13" int2,
"p24_7_14" int2,
"p24_8_1" int2,
"p24_8_2" varchar(20) DEFAULT NULL::character varying,
"p24_8_3" varchar(2) DEFAULT NULL::character varying,
"p24_8_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_8_5" varchar(2) DEFAULT NULL::character varying,
"p24_8_6" int2,
"p24_8_7" varchar(2) DEFAULT NULL::character varying,
"p24_8_8" int2,
"p24_8_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_8_10" varchar(2) DEFAULT NULL::character varying,
"p24_8_11" varchar(2) DEFAULT NULL::character varying,
"p24_8_12" int2,
"p24_8_13" int2,
"p24_8_14" int2,
"p24_9_1" int2,
"p24_9_2" varchar(20) DEFAULT NULL::character varying,
"p24_9_3" varchar(2) DEFAULT NULL::character varying,
"p24_9_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_9_5" varchar(2) DEFAULT NULL::character varying,
"p24_9_6" int2,
"p24_9_7" varchar(2) DEFAULT NULL::character varying,
"p24_9_8" int2,
"p24_9_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_9_10" varchar(2) DEFAULT NULL::character varying,
"p24_9_11" varchar(2) DEFAULT NULL::character varying,
"p24_9_12" int2,
"p24_9_13" int2,
"p24_9_14" int2,
"p24_10_1" int2,
"p24_10_2" varchar(20) DEFAULT NULL::character varying,
"p24_10_3" varchar(2) DEFAULT NULL::character varying,
"p24_10_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_10_5" varchar(2) DEFAULT NULL::character varying,
"p24_10_6" int2,
"p24_10_7" varchar(2) DEFAULT NULL::character varying,
"p24_10_8" int2,
"p24_10_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_10_10" varchar(2) DEFAULT NULL::character varying,
"p24_10_11" varchar(2) DEFAULT NULL::character varying,
"p24_10_12" int2,
"p24_10_13" int2,
"p24_10_14" int2,
"p24_11_1" int2,
"p24_11_2" varchar(20) DEFAULT NULL::character varying,
"p24_11_3" varchar(2) DEFAULT NULL::character varying,
"p24_11_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_11_5" varchar(2) DEFAULT NULL::character varying,
"p24_11_6" int2,
"p24_11_7" varchar(2) DEFAULT NULL::character varying,
"p24_11_8" int2,
"p24_11_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_11_10" varchar(2) DEFAULT NULL::character varying,
"p24_11_11" varchar(2) DEFAULT NULL::character varying,
"p24_11_12" int2,
"p24_11_13" int2,
"p24_11_14" int2,
"p24_12_1" int2,
"p24_12_2" varchar(20) DEFAULT NULL::character varying,
"p24_12_3" varchar(2) DEFAULT NULL::character varying,
"p24_12_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_12_5" varchar(2) DEFAULT NULL::character varying,
"p24_12_6" int2,
"p24_12_7" varchar(2) DEFAULT NULL::character varying,
"p24_12_8" int2,
"p24_12_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_12_10" varchar(2) DEFAULT NULL::character varying,
"p24_12_11" varchar(2) DEFAULT NULL::character varying,
"p24_12_12" int2,
"p24_12_13" int2,
"p24_12_14" int2,
"p24_13_1" int2,
"p24_13_2" varchar(20) DEFAULT NULL::character varying,
"p24_13_3" varchar(2) DEFAULT NULL::character varying,
"p24_13_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_13_5" varchar(2) DEFAULT NULL::character varying,
"p24_13_6" int2,
"p24_13_7" varchar(2) DEFAULT NULL::character varying,
"p24_13_8" int2,
"p24_13_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_13_10" varchar(2) DEFAULT NULL::character varying,
"p24_13_11" varchar(2) DEFAULT NULL::character varying,
"p24_13_12" int2,
"p24_13_13" int2,
"p24_13_14" int2,
"p24_14_1" int2,
"p24_14_2" varchar(20) DEFAULT NULL::character varying,
"p24_14_3" varchar(2) DEFAULT NULL::character varying,
"p24_14_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_14_5" varchar(2) DEFAULT NULL::character varying,
"p24_14_6" int2,
"p24_14_7" varchar(2) DEFAULT NULL::character varying,
"p24_14_8" int2,
"p24_14_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_14_10" varchar(2) DEFAULT NULL::character varying,
"p24_14_11" varchar(2) DEFAULT NULL::character varying,
"p24_14_12" int2,
"p24_14_13" int2,
"p24_14_14" int2,
"p24_15_1" int2,
"p24_15_2" varchar(20) DEFAULT NULL::character varying,
"p24_15_3" varchar(2) DEFAULT NULL::character varying,
"p24_15_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_15_5" varchar(2) DEFAULT NULL::character varying,
"p24_15_6" int2,
"p24_15_7" varchar(2) DEFAULT NULL::character varying,
"p24_15_8" int2,
"p24_15_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_15_10" varchar(2) DEFAULT NULL::character varying,
"p24_15_11" varchar(2) DEFAULT NULL::character varying,
"p24_15_12" int2,
"p24_15_13" int2,
"p24_15_14" int2,
"p24_16_1" int2,
"p24_16_2" varchar(20) DEFAULT NULL::character varying,
"p24_16_3" varchar(2) DEFAULT NULL::character varying,
"p24_16_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_16_5" varchar(2) DEFAULT NULL::character varying,
"p24_16_6" int2,
"p24_16_7" varchar(2) DEFAULT NULL::character varying,
"p24_16_8" int2,
"p24_16_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_16_10" varchar(2) DEFAULT NULL::character varying,
"p24_16_11" varchar(2) DEFAULT NULL::character varying,
"p24_16_12" int2,
"p24_16_13" int2,
"p24_16_14" int2,
"p24_17_1" int2,
"p24_17_2" varchar(20) DEFAULT NULL::character varying,
"p24_17_3" varchar(2) DEFAULT NULL::character varying,
"p24_17_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_17_5" varchar(2) DEFAULT NULL::character varying,
"p24_17_6" int2,
"p24_17_7" varchar(2) DEFAULT NULL::character varying,
"p24_17_8" int2,
"p24_17_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_17_10" varchar(2) DEFAULT NULL::character varying,
"p24_17_11" varchar(2) DEFAULT NULL::character varying,
"p24_17_12" int2,
"p24_17_13" int2,
"p24_17_14" int2,
"p24_18_1" int2,
"p24_18_2" varchar(20) DEFAULT NULL::character varying,
"p24_18_3" varchar(2) DEFAULT NULL::character varying,
"p24_18_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_18_5" varchar(2) DEFAULT NULL::character varying,
"p24_18_6" int2,
"p24_18_7" varchar(2) DEFAULT NULL::character varying,
"p24_18_8" int2,
"p24_18_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_18_10" varchar(2) DEFAULT NULL::character varying,
"p24_18_11" varchar(2) DEFAULT NULL::character varying,
"p24_18_12" int2,
"p24_18_13" int2,
"p24_18_14" int2,
"p24_19_1" int2,
"p24_19_2" varchar(20) DEFAULT NULL::character varying,
"p24_19_3" varchar(2) DEFAULT NULL::character varying,
"p24_19_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_19_5" varchar(2) DEFAULT NULL::character varying,
"p24_19_6" int2,
"p24_19_7" varchar(2) DEFAULT NULL::character varying,
"p24_19_8" int2,
"p24_19_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_19_10" varchar(2) DEFAULT NULL::character varying,
"p24_19_11" varchar(2) DEFAULT NULL::character varying,
"p24_19_12" int2,
"p24_19_13" int2,
"p24_19_14" int2,
"p24_20_1" int2,
"p24_20_2" varchar(20) DEFAULT NULL::character varying,
"p24_20_3" varchar(2) DEFAULT NULL::character varying,
"p24_20_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_20_5" varchar(2) DEFAULT NULL::character varying,
"p24_20_6" int2,
"p24_20_7" varchar(2) DEFAULT NULL::character varying,
"p24_20_8" int2,
"p24_20_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_20_10" varchar(2) DEFAULT NULL::character varying,
"p24_20_11" varchar(2) DEFAULT NULL::character varying,
"p24_20_12" int2,
"p24_20_13" int2,
"p24_20_14" int2,
"p24_21_1" int2,
"p24_21_2" varchar(20) DEFAULT NULL::character varying,
"p24_21_3" varchar(2) DEFAULT NULL::character varying,
"p24_21_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_21_5" varchar(2) DEFAULT NULL::character varying,
"p24_21_6" int2,
"p24_21_7" varchar(2) DEFAULT NULL::character varying,
"p24_21_8" int2,
"p24_21_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_21_10" varchar(2) DEFAULT NULL::character varying,
"p24_21_11" varchar(2) DEFAULT NULL::character varying,
"p24_21_12" int2,
"p24_21_13" int2,
"p24_21_14" int2,
"p24_22_1" int2,
"p24_22_2" varchar(20) DEFAULT NULL::character varying,
"p24_22_3" varchar(2) DEFAULT NULL::character varying,
"p24_22_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_22_5" varchar(2) DEFAULT NULL::character varying,
"p24_22_6" int2,
"p24_22_7" varchar(2) DEFAULT NULL::character varying,
"p24_22_8" int2,
"p24_22_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_22_10" varchar(2) DEFAULT NULL::character varying,
"p24_22_11" varchar(2) DEFAULT NULL::character varying,
"p24_22_12" int2,
"p24_22_13" int2,
"p24_22_14" int2,
"p24_23_1" int2,
"p24_23_2" varchar(20) DEFAULT NULL::character varying,
"p24_23_3" varchar(2) DEFAULT NULL::character varying,
"p24_23_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_23_5" varchar(2) DEFAULT NULL::character varying,
"p24_23_6" int2,
"p24_23_7" varchar(2) DEFAULT NULL::character varying,
"p24_23_8" int2,
"p24_23_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_23_10" varchar(2) DEFAULT NULL::character varying,
"p24_23_11" varchar(2) DEFAULT NULL::character varying,
"p24_23_12" int2,
"p24_23_13" int2,
"p24_23_14" int2,
"p24_24_1" int2,
"p24_24_2" varchar(20) DEFAULT NULL::character varying,
"p24_24_3" varchar(2) DEFAULT NULL::character varying,
"p24_24_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_24_5" varchar(2) DEFAULT NULL::character varying,
"p24_24_6" int2,
"p24_24_7" varchar(2) DEFAULT NULL::character varying,
"p24_24_8" int2,
"p24_24_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_24_10" varchar(2) DEFAULT NULL::character varying,
"p24_24_11" varchar(2) DEFAULT NULL::character varying,
"p24_24_12" int2,
"p24_24_13" int2,
"p24_24_14" int2,
"p24_25_1" int2,
"p24_25_2" varchar(20) DEFAULT NULL::character varying,
"p24_25_3" varchar(2) DEFAULT NULL::character varying,
"p24_25_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_25_5" varchar(2) DEFAULT NULL::character varying,
"p24_25_6" int2,
"p24_25_7" varchar(2) DEFAULT NULL::character varying,
"p24_25_8" int2,
"p24_25_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_25_10" varchar(2) DEFAULT NULL::character varying,
"p24_25_11" varchar(2) DEFAULT NULL::character varying,
"p24_25_12" int2,
"p24_25_13" int2,
"p24_25_14" int2,
"p24_26_1" int2,
"p24_26_2" varchar(20) DEFAULT NULL::character varying,
"p24_26_3" varchar(2) DEFAULT NULL::character varying,
"p24_26_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_26_5" varchar(2) DEFAULT NULL::character varying,
"p24_26_6" int2,
"p24_26_7" varchar(2) DEFAULT NULL::character varying,
"p24_26_8" int2,
"p24_26_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_26_10" varchar(2) DEFAULT NULL::character varying,
"p24_26_11" varchar(2) DEFAULT NULL::character varying,
"p24_26_12" int2,
"p24_26_13" int2,
"p24_26_14" int2,
"p24_27_1" int2,
"p24_27_2" varchar(20) DEFAULT NULL::character varying,
"p24_27_3" varchar(2) DEFAULT NULL::character varying,
"p24_27_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_27_5" varchar(2) DEFAULT NULL::character varying,
"p24_27_6" int2,
"p24_27_7" varchar(2) DEFAULT NULL::character varying,
"p24_27_8" int2,
"p24_27_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_27_10" varchar(2) DEFAULT NULL::character varying,
"p24_27_11" varchar(2) DEFAULT NULL::character varying,
"p24_27_12" int2,
"p24_27_13" int2,
"p24_27_14" int2,
"p24_28_1" int2,
"p24_28_2" varchar(20) DEFAULT NULL::character varying,
"p24_28_3" varchar(2) DEFAULT NULL::character varying,
"p24_28_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_28_5" varchar(2) DEFAULT NULL::character varying,
"p24_28_6" int2,
"p24_28_7" varchar(2) DEFAULT NULL::character varying,
"p24_28_8" int2,
"p24_28_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_28_10" varchar(2) DEFAULT NULL::character varying,
"p24_28_11" varchar(2) DEFAULT NULL::character varying,
"p24_28_12" int2,
"p24_28_13" int2,
"p24_28_14" int2,
"p24_29_1" int2,
"p24_29_2" varchar(20) DEFAULT NULL::character varying,
"p24_29_3" varchar(2) DEFAULT NULL::character varying,
"p24_29_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_29_5" varchar(2) DEFAULT NULL::character varying,
"p24_29_6" int2,
"p24_29_7" varchar(2) DEFAULT NULL::character varying,
"p24_29_8" int2,
"p24_29_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_29_10" varchar(2) DEFAULT NULL::character varying,
"p24_29_11" varchar(2) DEFAULT NULL::character varying,
"p24_29_12" int2,
"p24_29_13" int2,
"p24_29_14" int2,
"p24_30_1" int2,
"p24_30_2" varchar(20) DEFAULT NULL::character varying,
"p24_30_3" varchar(2) DEFAULT NULL::character varying,
"p24_30_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_30_5" varchar(2) DEFAULT NULL::character varying,
"p24_30_6" int2,
"p24_30_7" varchar(2) DEFAULT NULL::character varying,
"p24_30_8" int2,
"p24_30_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_30_10" varchar(2) DEFAULT NULL::character varying,
"p24_30_11" varchar(2) DEFAULT NULL::character varying,
"p24_30_12" int2,
"p24_30_13" int2,
"p24_30_14" int2,
"p24_31_1" int2,
"p24_31_2" varchar(20) DEFAULT NULL::character varying,
"p24_31_3" varchar(2) DEFAULT NULL::character varying,
"p24_31_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_31_5" varchar(2) DEFAULT NULL::character varying,
"p24_31_6" int2,
"p24_31_7" varchar(2) DEFAULT NULL::character varying,
"p24_31_8" int2,
"p24_31_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_31_10" varchar(2) DEFAULT NULL::character varying,
"p24_31_11" varchar(2) DEFAULT NULL::character varying,
"p24_31_12" int2,
"p24_31_13" int2,
"p24_31_14" int2,
"p24_32_1" int2,
"p24_32_2" varchar(20) DEFAULT NULL::character varying,
"p24_32_3" varchar(2) DEFAULT NULL::character varying,
"p24_32_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_32_5" varchar(2) DEFAULT NULL::character varying,
"p24_32_6" int2,
"p24_32_7" varchar(2) DEFAULT NULL::character varying,
"p24_32_8" int2,
"p24_32_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_32_10" varchar(2) DEFAULT NULL::character varying,
"p24_32_11" varchar(2) DEFAULT NULL::character varying,
"p24_32_12" int2,
"p24_32_13" int2,
"p24_32_14" int2,
"p24_33_1" int2,
"p24_33_2" varchar(20) DEFAULT NULL::character varying,
"p24_33_3" varchar(2) DEFAULT NULL::character varying,
"p24_33_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_33_5" varchar(2) DEFAULT NULL::character varying,
"p24_33_6" int2,
"p24_33_7" varchar(2) DEFAULT NULL::character varying,
"p24_33_8" int2,
"p24_33_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_33_10" varchar(2) DEFAULT NULL::character varying,
"p24_33_11" varchar(2) DEFAULT NULL::character varying,
"p24_33_12" int2,
"p24_33_13" int2,
"p24_33_14" int2,
"p24_34_1" int2,
"p24_34_2" varchar(20) DEFAULT NULL::character varying,
"p24_34_3" varchar(2) DEFAULT NULL::character varying,
"p24_34_4" numeric(8,2) DEFAULT NULL::numeric,
"p24_34_5" varchar(2) DEFAULT NULL::character varying,
"p24_34_6" int2,
"p24_34_7" varchar(2) DEFAULT NULL::character varying,
"p24_34_8" int2,
"p24_34_9" numeric(8,2) DEFAULT NULL::numeric,
"p24_34_10" varchar(2) DEFAULT NULL::character varying,
"p24_34_11" varchar(2) DEFAULT NULL::character varying,
"p24_34_12" int2,
"p24_34_13" int2,
"p24_34_14" int2,
"p25_1" int2,
"p25_1_1" varchar(20) DEFAULT NULL::character varying,
"p25_1_2" numeric(8,2) DEFAULT NULL::numeric,
"p25_1_3" varchar(3) DEFAULT NULL::character varying,
"p25_2_1" varchar(20) DEFAULT NULL::character varying,
"p25_2_2" numeric(8,2) DEFAULT NULL::numeric,
"p25_2_3" varchar(3) DEFAULT NULL::character varying,
"p25_3_1" varchar(20) DEFAULT NULL::character varying,
"p25_3_2" numeric(8,2) DEFAULT NULL::numeric,
"p25_3_3" varchar(3) DEFAULT NULL::character varying,
"p25_4_1" varchar(20) DEFAULT NULL::character varying,
"p25_4_2" numeric(8,2) DEFAULT NULL::numeric,
"p25_4_3" varchar(3) DEFAULT NULL::character varying,
"p25_5_1" varchar(20) DEFAULT NULL::character varying,
"p25_5_2" numeric(8,2) DEFAULT NULL::numeric,
"p25_5_3" varchar(3) DEFAULT NULL::character varying,
"p26_1" int2,
"p26_1_1" varchar(20) DEFAULT NULL::character varying,
"p26_1_2" numeric(8,2) DEFAULT NULL::numeric,
"p26_1_3" varchar(3) DEFAULT NULL::character varying,
"p26_2_1" varchar(20) DEFAULT NULL::character varying,
"p26_2_2" numeric(8,2) DEFAULT NULL::numeric,
"p26_2_3" varchar(3) DEFAULT NULL::character varying,
"p26_3_1" varchar(20) DEFAULT NULL::character varying,
"p26_3_2" numeric(8,2) DEFAULT NULL::numeric,
"p26_3_3" varchar(3) DEFAULT NULL::character varying,
"p26_4_1" varchar(20) DEFAULT NULL::character varying,
"p26_4_2" numeric(8,2) DEFAULT NULL::numeric,
"p26_4_3" varchar(3) DEFAULT NULL::character varying,
"p26_5_1" varchar(20) DEFAULT NULL::character varying,
"p26_5_2" numeric(8,2) DEFAULT NULL::numeric,
"p26_5_3" varchar(3) DEFAULT NULL::character varying,
"p27_1" int2,
"p27_1_1" varchar(20) DEFAULT NULL::character varying,
"p27_1_2" numeric(8,2) DEFAULT NULL::numeric,
"p27_1_3" varchar(3) DEFAULT NULL::character varying,
"p27_2_1" varchar(20) DEFAULT NULL::character varying,
"p27_2_2" numeric(8,2) DEFAULT NULL::numeric,
"p27_2_3" varchar(3) DEFAULT NULL::character varying,
"p27_3_1" varchar(20) DEFAULT NULL::character varying,
"p27_3_2" numeric(8,2) DEFAULT NULL::numeric,
"p27_3_3" varchar(3) DEFAULT NULL::character varying,
"p27_4_1" varchar(20) DEFAULT NULL::character varying,
"p27_4_2" numeric(8,2) DEFAULT NULL::numeric,
"p27_4_3" varchar(3) DEFAULT NULL::character varying,
"p27_5_1" varchar(20) DEFAULT NULL::character varying,
"p27_5_2" numeric(8,2) DEFAULT NULL::numeric,
"p27_5_3" varchar(3) DEFAULT NULL::character varying,
"estado" varchar(5) DEFAULT NULL::character varying,
"fecharegistro" timestamp(6),
"usuarioregistro" varchar(15) DEFAULT NULL::character varying,
"ipregistro" varchar(20) DEFAULT NULL::character varying,
"fechamodificacion" timestamp(6),
"usuariomodificacion" varchar(15) DEFAULT NULL::character varying,
"ipmodificacion" varchar(20) DEFAULT NULL::character varying,
"tipoaplicacion" varchar(5) DEFAULT NULL::character varying,
"foliocomunal" varchar(6)
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of t_boletaproductor_p1
-- ----------------------------
INSERT INTO "public"."t_boletaproductor_p1" VALUES ('<br/>', '000001', '01', '1', '1', '1234', '01', '01', '01', '01', '01', '1', '11', 'SU', 'MANTA', '12', 'QWE', 'QWEQ', 'QWEQW', 'QWEQW', 'QWEQWE', null, null, null, null, null, '1', '1', '123.00', '11', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-04 16:30:26.344349', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p1" VALUES ('<br/>', '000002', '01', '1', '1', '1233', '01', '01', '01', '01', '01', '1', '11', 'SU', 'DEBUGADO', '01', 'DEBUG', 'DE', 'DE', 'DE', 'DE', '1', 'DE', '1', '1', '1', '1', '12', '123.00', '12', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-04 16:43:55.542325', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p1" VALUES ('<br/>', '000003', '01', '1', '1', '1231', '01', '01', '01', '01', '01', '1', '11', 'SU', 'DEBUG 2', '12', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-04 17:00:46.052349', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p1" VALUES ('', '000004', '01', '4', '4', '4444', '01', '01', '01', '01', '01', '1', '11', 'SU', 'DEBUG 4', '02', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-04 17:11:37.855724', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p1" VALUES ('', '000005', '01', '', '', '', '01', '01', '01', '01', '01', '1', '11', 'su', '', '', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-04 17:25:49.638773', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p1" VALUES ('', '000006', '01', '', '', '', '01', '01', '01', '01', '01', '1', '11', 'SU', '', '', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-04 18:05:23.633861', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p1" VALUES ('', '000007', '11', '', '', '', '01', '01', '01', '01', '01', '1', '01', 'SUC', '', '', 'DEBUG', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-04 18:22:55.230344', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p1" VALUES ('', '000123', '01', '1', '1', '1231', '01', '01', '01', '01', '01', '1', '1', 'COMUNIDAD SUCRE', 'PRUEBA', '12', 'QW', 'QW', 'QW', 'QW', 'QW', '1', 'QW', '1', '1', '1', '1', '1', '132.00', '12', '123.00', '12', '123.00', '12', '123.00', '12', '123.00', '12', '123.00', '12', '2', '2', '2', '2', '1', '1', 'QW', '123.00', '12', '1', '12', '123.00', '12', '12', '1', '1', '1', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6', 'QW', '123.00', '12', '1', '12', '123.00', '12', '12', '1', '1', '1', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-03 11:11:36.250972', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p1" VALUES ('', '000321', '11', '1', '1', '1233', '01', '01', '01', '01', '01', '1', '01', 'SUC', 'OEIWRU', '12', 'PRUEBA GUEEK', 'WEE', 'WEE', 'WEE', 'WEE', '1', 'WEE', '1', '1', '1', '1', '12', '213.00', '12', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-04 16:00:43.718856', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p1" VALUES ('', '000456', '01', '1', '1', '1321', '01', '01', '01', '02', '01', '1', '02', 'DOS TRES', 'CUATRO', '12', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-03 16:19:51.864107', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p1" VALUES ('', '000789', '01', '1', '1', '1234', '01', '01', '01', '02', '01', '1', '02', 'DOS TRES', 'CUATRO', '12', 'DAS', 'DAS', 'DAS', 'DAS', 'DAS', '1', 'DAS', '1', '1', '1', '1', '1', '12.00', '21', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-04 10:34:10.268756', 'prueba-trans', '127.0.0.1', null, null, null, null, null);

-- ----------------------------
-- Alter Sequences Owned By 
-- ----------------------------

-- ----------------------------
-- Indexes structure for table t_boletaproductor_p1
-- ----------------------------
CREATE INDEX "t_boletaproductor_p1_docid_idx" ON "public"."t_boletaproductor_p1" USING btree ("docid");

-- ----------------------------
-- Primary Key structure for table "public"."t_boletaproductor_p1"
-- ----------------------------
ALTER TABLE "public"."t_boletaproductor_p1" ADD PRIMARY KEY ("folio");
