/*
Navicat PGSQL Data Transfer

Source Server         : postgres-vladi
Source Server Version : 90109
Source Host           : 192.168.78.160:5432
Source Database       : bdca
Source Schema         : public

Target Server Type    : PGSQL
Target Server Version : 90109
File Encoding         : 65001

Date: 2013-12-06 19:56:42
*/


-- ----------------------------
-- Table structure for "public"."t_boletaproductor_p2"
-- ----------------------------
DROP TABLE "public"."t_boletaproductor_p2";
CREATE TABLE "public"."t_boletaproductor_p2" (
"docid" varchar(20) DEFAULT nextval('t_boletaproductor_p2_docid_seq'::regclass) NOT NULL,
"folio" varchar(6) NOT NULL,
"numerobrigada" varchar(4) NOT NULL,
"numeroempadronador" varchar(2) NOT NULL,
"numerosegmento" varchar(2) DEFAULT ''::character varying NOT NULL,
"numerohojacontrol" varchar(6) NOT NULL,
"codigodepartamento" varchar(2) NOT NULL,
"codigoprovincia" varchar(2) NOT NULL,
"codigomunicipio" varchar(2) NOT NULL,
"codigoareacensal" varchar(2) NOT NULL,
"codigocantoncensal" varchar(2) NOT NULL,
"tipoupa" varchar(2) NOT NULL,
"numeroorden" varchar(2) DEFAULT NULL::character varying,
"nombreespecifico" varchar(150) NOT NULL,
"nombrelocalidad" varchar(150) DEFAULT NULL::character varying,
"numerodistritomunicipal" varchar(2) DEFAULT NULL::character varying,
"p28_1" int2,
"p28_1_1" numeric(8,2) DEFAULT NULL::numeric,
"p28_1_2" varchar(2) DEFAULT NULL::character varying,
"p28_2_1" numeric(8,2) DEFAULT NULL::numeric,
"p28_2_2" varchar(2) DEFAULT NULL::character varying,
"p28_3_1" numeric(8,2) DEFAULT NULL::numeric,
"p28_3_2" varchar(2) DEFAULT NULL::character varying,
"p28_4_1" numeric(8,2) DEFAULT NULL::numeric,
"p28_4_2" varchar(2) DEFAULT NULL::character varying,
"p28_5_1" numeric(8,2) DEFAULT NULL::numeric,
"p28_5_2" varchar(2) DEFAULT NULL::character varying,
"p29_1" int2,
"p29_1_1" varchar(20) DEFAULT NULL::character varying,
"p29_1_2" int2,
"p29_2_1" varchar(20) DEFAULT NULL::character varying,
"p29_2_2" int2,
"p29_3_1" varchar(20) DEFAULT NULL::character varying,
"p29_3_2" int2,
"p29_4_1" varchar(20) DEFAULT NULL::character varying,
"p29_4_2" int2,
"p29_5_1" varchar(20) DEFAULT NULL::character varying,
"p29_5_2" int2,
"p30_1" int2,
"p30_2" varchar(25) DEFAULT NULL::character varying,
"p30_3" varchar(25) DEFAULT NULL::character varying,
"p30_4" varchar(25) DEFAULT NULL::character varying,
"p30_5" varchar(25) DEFAULT NULL::character varying,
"p30_6" varchar(25) DEFAULT NULL::character varying,
"p31_1" int2,
"p31_2" int2,
"p31_3" int2,
"p32" int2,
"p33" int2,
"p34" int2,
"p35" int2,
"p36" int2,
"p37_1" int2,
"p37_1_1" varchar(20) DEFAULT NULL::character varying,
"p37_1_2" int2,
"p37_2_1" varchar(20) DEFAULT NULL::character varying,
"p37_2_2" int2,
"p37_3_1" varchar(20) DEFAULT NULL::character varying,
"p37_3_2" int2,
"p37_4_1" varchar(20) DEFAULT NULL::character varying,
"p37_4_2" int2,
"p37_5_1" varchar(20) DEFAULT NULL::character varying,
"p37_5_2" int2,
"p38_1_1" int2,
"p38_1_2" int2,
"p38_1_3" int2,
"p38_2_1" int2,
"p38_2_2" int2,
"p38_2_3" int2,
"p38_3_1" int2,
"p38_3_2" int2,
"p38_3_3" int2,
"p38_4_1" int2,
"p38_4_2" int2,
"p38_4_3" int2,
"p39_1_1" int2,
"p39_1_2" int2,
"p39_1_3" int2,
"p39_2_1" int2,
"p39_2_2" int2,
"p39_2_3" int2,
"p39_3_1" int2,
"p39_3_2" int2,
"p39_3_3" int2,
"p39_4_1" int2,
"p39_4_2" int2,
"p39_4_3" int2,
"p39_5_1" int2,
"p39_5_2" int2,
"p39_5_3" int2,
"p39_6_1" int2,
"p39_6_2" int2,
"p39_6_3" int2,
"p39_7_1" int2,
"p39_7_2" int2,
"p39_7_3" int2,
"p39_8_1" int2,
"p39_8_2" int2,
"p39_8_3" int2,
"p39_9_1" int2,
"p39_9_2" int2,
"p39_9_3" int2,
"p39_10_1" int2,
"p39_10_2" int2,
"p39_10_3" int2,
"p39_11_1" int2,
"p39_11_2" int2,
"p39_11_3" int2,
"p39_12_1" int2,
"p39_12_2" int2,
"p39_12_3" int2,
"p39_13_1" int2,
"p39_13_2" int2,
"p39_13_3" int2,
"p39_14_1" int2,
"p39_14_2" int2,
"p39_14_3" int2,
"p39_15_1" int2,
"p39_15_2" int2,
"p39_15_3" int2,
"p39_16_1" int2,
"p39_16_2" int2,
"p39_16_3" int2,
"p39_17_1" int2,
"p39_17_2" int2,
"p39_17_3" int2,
"p39_18_1" int2,
"p39_18_2" int2,
"p39_18_3" int2,
"p40" int2,
"p41_1_1" int2,
"p41_1_2" int2,
"p41_1_3" int2,
"p41_2_1" int2,
"p41_2_2" int2,
"p41_2_3" int2,
"p41_3_1" int2,
"p41_3_2" int2,
"p41_3_3" int2,
"p41_4_1" int2,
"p41_4_2" int2,
"p41_4_3" int2,
"p41_5_1" int2,
"p41_5_2" int2,
"p41_5_3" int2,
"p41_6_1" int2,
"p41_6_2" int2,
"p41_6_3" int2,
"p41_7_1" int2,
"p41_7_2" int2,
"p41_7_3" int2,
"p41_8_1" int2,
"p41_8_2" int2,
"p41_8_3" int2,
"p41_9_1" int2,
"p41_9_2" int2,
"p41_9_3" int2,
"p41_10_1" int2,
"p41_10_2" int2,
"p41_10_3" int2,
"p41_11_1" int2,
"p41_11_2" int2,
"p41_11_3" int2,
"p41_12_1" int2,
"p41_12_2" int2,
"p41_12_3" int2,
"p42" int2,
"p43" int2,
"p44" int2,
"p45_1" int2,
"p45_2" int2,
"p45_3" int2,
"p46" int2,
"p47_1" int2,
"p47_2" int2,
"p47_3" int2,
"p48" int2,
"p49_1" int2,
"p49_2" int2,
"p49_3" int2,
"p50" int2,
"p51_1_1" int2,
"p51_1_2" int2,
"p51_1_3" int2,
"p51_2_1" int2,
"p51_2_2" int2,
"p51_2_3" int2,
"p51_3_1" int2,
"p51_3_2" int2,
"p51_3_3" int2,
"p51_4_1" int2,
"p51_4_2" int2,
"p51_4_3" int2,
"p52_1" int2,
"p52_2" int2,
"p52_3" int2,
"p53_1" int2,
"p53_2" int2,
"p53_3" int2,
"p54" int2,
"p55_1_1" int2,
"p55_1_2" int2,
"p55_1_3" int2,
"p55_1_4" int2,
"p55_1_5" int2,
"p55_2_1" int2,
"p55_2_2" int2,
"p55_2_3" int2,
"p55_2_4" int2,
"p55_2_5" int2,
"p55_3_1" int2,
"p55_3_2" int2,
"p55_3_3" int2,
"p55_3_4" int2,
"p55_3_5" int2,
"p56" int2,
"p57_1_1" int2,
"p57_1_2" int2,
"p57_1_3" int2,
"p57_2_1" int2,
"p57_2_2" int2,
"p57_2_3" int2,
"p57_3_1" int2,
"p57_3_2" int2,
"p57_3_3" int2,
"p57_4_1" int2,
"p57_4_2" int2,
"p57_4_3" int2,
"p58_1" int2,
"p58_2" int2,
"p58_3" int2,
"p59" int2,
"p60_1_1" int2,
"p60_1_2" int2,
"p60_1_3" int2,
"p60_2_1" int2,
"p60_2_2" int2,
"p60_2_3" int2,
"p60_3_1" int2,
"p60_3_2" int2,
"p60_3_3" int2,
"p60_4_1" int2,
"p60_4_2" int2,
"p60_4_3" int2,
"p61_1" int2,
"p61_2" int2,
"p61_3" int2,
"p62" int2,
"p63_1_1" int2,
"p63_1_2" int2,
"p63_1_3" int2,
"p63_1_4" int2,
"p63_2_1" int2,
"p63_2_2" int2,
"p63_2_3" int2,
"p63_2_4" int2,
"p63_3_1" int2,
"p63_3_2" int2,
"p63_3_3" int2,
"p63_3_4" int2,
"p63_4_1" int2,
"p63_4_2" int2,
"p63_4_3" int2,
"p63_4_4" int2,
"p63_5_1" int2,
"p63_5_2" int2,
"p63_5_3" int2,
"p63_5_4" int2,
"p63_6_1" int2,
"p63_6_2" int2,
"p63_6_3" int2,
"p63_6_4" int2,
"p63_7_1" int2,
"p63_7_2" int2,
"p63_7_3" int2,
"p63_7_4" int2,
"p63_8_1" int2,
"p63_8_2" int2,
"p63_8_3" int2,
"p63_8_4" int2,
"p63_9_1" int2,
"p63_9_2" int2,
"p63_9_3" int2,
"p63_9_4" int2,
"p64_1" int2,
"p64_2" int2,
"p64_3" int2,
"p65_1" int2,
"p65_2" int2,
"p65_3" int2,
"p66" int2,
"p67_1_1" int2,
"p67_1_2" int2,
"p67_1_3" int2,
"p67_1_4" int2,
"p67_2_1" int2,
"p67_2_2" int2,
"p67_2_3" int2,
"p67_2_4" int2,
"p67_3_1" int2,
"p67_3_2" int2,
"p67_3_3" int2,
"p67_3_4" int2,
"p67_4_1" int2,
"p67_4_2" int2,
"p67_4_3" int2,
"p67_4_4" int2,
"p67_5_1" int2,
"p67_5_2" int2,
"p67_5_3" int2,
"p67_5_4" int2,
"p67_6_1" int2,
"p67_6_2" int2,
"p67_6_3" int2,
"p67_6_4" int2,
"p67_7_1" int2,
"p67_7_2" int2,
"p67_7_3" int2,
"p67_7_4" int2,
"p67_8_1" int2,
"p67_8_2" int2,
"p67_8_3" int2,
"p67_8_4" int2,
"p67_9_1" int2,
"p67_9_2" int2,
"p67_9_3" int2,
"p67_9_4" int2,
"p68_1" int2,
"p68_2" int2,
"p68_3" int2,
"p69_1" int2,
"p69_2" int2,
"p69_3" int2,
"p70_1" int2,
"p70_2" int2,
"p70_3" int2,
"p70_4" int2,
"p70_5" int2,
"p71_1" int2,
"p71_2" int2,
"p71_3" int2,
"p72" int2,
"p73_1" int2,
"p73_2" int2,
"p73_3" int2,
"p73_4" int2,
"p73_5" int2,
"p73_6" int2,
"p73_7" int2,
"p73_8" int2,
"p73_9" int2,
"p73_10" int2,
"p74_1_1" int2,
"p74_1_2" int2,
"p74_1_3" int2,
"p74_2_1" int2,
"p74_2_2" int2,
"p74_2_3" int2,
"p74_3_1" int2,
"p74_3_2" int2,
"p74_3_3" int2,
"p74_4_1" int2,
"p74_4_2" int2,
"p74_4_3" int2,
"p75" int2,
"p76_1" int2,
"p76_2" int2,
"p76_3" int2,
"p76_4" int2,
"p77_1" int2,
"p77_2" int2,
"p77_3" int2,
"p78" int2,
"p79_1" int2,
"p79_2" int2,
"p80" int2,
"p81_1" int2,
"p81_2" varchar(2) DEFAULT NULL::character varying,
"p82_1" int2,
"p82_2" int2,
"p82_3" int2,
"p83_1" int2,
"p83_2" int2,
"p83_3" int2,
"p83_4" int2,
"p83_5" int2,
"p83_6" int2,
"p83_7" int2,
"p84_1" int2,
"p84_2" int2,
"p85_1" int2,
"p85_2" int2,
"p85_3" int2,
"p86_1_1" int2,
"p86_1_2" int2,
"p86_1_3" int2,
"p86_2_1" int2,
"p86_2_2" int2,
"p86_2_3" int2,
"p86_3_1" int2,
"p86_3_2" int2,
"p86_3_3" int2,
"p86_4_1" int2,
"p86_4_2" int2,
"p86_4_3" int2,
"p86_5_1" int2,
"p86_5_2" int2,
"p86_5_3" int2,
"p86_6_1" int2,
"p86_6_2" int2,
"p86_6_3" int2,
"p86_7_1" int2,
"p86_7_2" int2,
"p86_7_3" int2,
"p87_1_1" int2,
"p87_1_2" int2,
"p87_1_3" int2,
"p87_2_1" int2,
"p87_2_2" int2,
"p87_2_3" int2,
"p88" int2,
"p89_1" int2,
"p89_2" int2,
"p89_3" int2,
"p90_1" int2,
"p90_2" int2,
"p90_3" int2,
"p90_4" int2,
"p90_5" int2,
"p90_6" int2,
"p90_7" int2,
"p90_8" int2,
"p90_9" int2,
"p90_10" int2,
"p91" int2,
"p92_1" varchar(25) DEFAULT NULL::character varying,
"p92_2" varchar(25) DEFAULT NULL::character varying,
"p92_3" varchar(25) DEFAULT NULL::character varying,
"p92_4" varchar(25) DEFAULT NULL::character varying,
"p93_1" int2,
"p93_2" int2,
"p94" int2,
"p95" int2,
"p96_1_1" varchar(15) DEFAULT NULL::character varying,
"p96_1_2" int2,
"p96_1_3" varchar(2) DEFAULT NULL::character varying,
"p96_1_4" int2,
"p96_2_1" varchar(15) DEFAULT NULL::character varying,
"p96_2_2" int2,
"p96_2_3" varchar(2) DEFAULT NULL::character varying,
"p96_2_4" int2,
"p96_3_1" varchar(15) DEFAULT NULL::character varying,
"p96_3_2" int2,
"p96_3_3" varchar(2) DEFAULT NULL::character varying,
"p96_3_4" int2,
"p96_4_1" varchar(15) DEFAULT NULL::character varying,
"p96_4_2" int2,
"p96_4_3" varchar(2) DEFAULT NULL::character varying,
"p96_4_4" int2,
"p96_5_1" varchar(15) DEFAULT NULL::character varying,
"p96_5_2" int2,
"p96_5_3" varchar(2) DEFAULT NULL::character varying,
"p96_5_4" int2,
"p97" int2,
"p98_1_1" varchar(20) DEFAULT NULL::character varying,
"p98_1_2" varchar(2) DEFAULT NULL::character varying,
"p98_1_3" varchar(2) DEFAULT NULL::character varying,
"p98_2_1" varchar(20) DEFAULT NULL::character varying,
"p98_2_2" varchar(2) DEFAULT NULL::character varying,
"p98_2_3" varchar(2) DEFAULT NULL::character varying,
"p98_3_1" varchar(20) DEFAULT NULL::character varying,
"p98_3_2" varchar(2) DEFAULT NULL::character varying,
"p98_3_3" varchar(2) DEFAULT NULL::character varying,
"p98_4_1" varchar(20) DEFAULT NULL::character varying,
"p98_4_2" varchar(2) DEFAULT NULL::character varying,
"p98_4_3" varchar(2) DEFAULT NULL::character varying,
"p99_1" int2,
"p99_2" int2,
"p100" int2,
"p101_1_1" varchar(20) DEFAULT NULL::character varying,
"p101_1_2" varchar(2) DEFAULT NULL::character varying,
"p101_1_3" varchar(2) DEFAULT NULL::character varying,
"p101_2_1" varchar(20) DEFAULT NULL::character varying,
"p101_2_2" varchar(2) DEFAULT NULL::character varying,
"p101_2_3" varchar(2) DEFAULT NULL::character varying,
"p101_3_1" varchar(20) DEFAULT NULL::character varying,
"p101_3_2" varchar(2) DEFAULT NULL::character varying,
"p101_3_3" varchar(2) DEFAULT NULL::character varying,
"p101_4_1" varchar(20) DEFAULT NULL::character varying,
"p101_4_2" varchar(2) DEFAULT NULL::character varying,
"p101_4_3" varchar(2) DEFAULT NULL::character varying,
"p102_1" int2,
"p102_2" int2,
"p102_3" int2,
"p103" int2,
"p104_1" varchar(30) DEFAULT NULL::character varying,
"p104_2" varchar(30) DEFAULT NULL::character varying,
"p104_3" varchar(30) DEFAULT NULL::character varying,
"p104_4" varchar(30) DEFAULT NULL::character varying,
"p105_1" int2,
"p105_2" int2,
"p105_3" int2,
"p106" int2,
"p107_1_1" int2,
"p107_1_2" int2,
"p107_1_3" int2,
"p107_1_4" int2,
"p107_1_5" int2,
"p107_1_6" int2,
"p107_2_1" int2,
"p107_2_2" int2,
"p107_2_3" int2,
"p107_2_4" int2,
"p107_2_5" int2,
"p107_2_6" int2,
"p107_3_1" int2,
"p107_3_2" int2,
"p107_3_3" int2,
"p107_3_4" int2,
"p107_3_5" int2,
"p107_3_6" int2,
"p107_4_1" int2,
"p107_4_2" int2,
"p107_4_3" int2,
"p107_4_4" int2,
"p107_4_5" int2,
"p107_4_6" int2,
"p107_5_1" int2,
"p107_5_2" int2,
"p107_5_3" int2,
"p107_5_4" int2,
"p107_5_5" int2,
"p107_5_6" int2,
"p108" int2,
"p109" int2,
"p110_1" int2,
"p110_2" int2,
"p111_1" int2,
"p111_2" int2,
"p111_3" int2,
"p111_4" int2,
"p112_1" int2,
"p112_2" int2,
"p112_3" int2,
"p113" int2,
"p114_1" varchar(30) DEFAULT NULL::character varying,
"p114_2" varchar(30) DEFAULT NULL::character varying,
"p114_3" varchar(30) DEFAULT NULL::character varying,
"p115_1_1" int2,
"p115_1_2" int2,
"p115_1_3" int2,
"p115_2_1" int2,
"p115_2_2" int2,
"p115_2_3" int2,
"p115_3_1" int2,
"p115_3_2" int2,
"p115_3_3" int2,
"p115_4_1" int2,
"p115_4_2" int2,
"p115_4_3" int2,
"p115_5_1" int2,
"p115_5_2" int2,
"p115_5_3" int2,
"p115_6_1" int2,
"p115_6_2" int2,
"p115_6_3" int2,
"p115_7_1" int2,
"p115_7_2" int2,
"p115_7_3" int2,
"p116_1_1" int2,
"p116_1_2" int2,
"p116_1_3" int2,
"p116_2_1" int2,
"p116_2_2" int2,
"p116_2_3" int2,
"p116_3_1" int2,
"p116_3_2" int2,
"p116_3_3" int2,
"p116_4_1" int2,
"p116_4_2" int2,
"p116_4_3" int2,
"p116_5_1" int2,
"p116_5_2" int2,
"p116_5_3" int2,
"p116_6_1" int2,
"p116_6_2" int2,
"p116_6_3" int2,
"p116_7_1" int2,
"p116_7_2" int2,
"p116_7_3" int2,
"p117_1" int2,
"p117_2" int2,
"p117_3" int2,
"p117_4" int2,
"p117_5" int2,
"p117_6" int2,
"p117_7" int2,
"p117_8" int2,
"p118" int2,
"p119" int2,
"p120" int2,
"p121" int2,
"p122" int2,
"p123_1" int2,
"p123_2" int2,
"p124_1" int2,
"p124_1_1" int2,
"p124_1_2" int2,
"p124_1_3" int2,
"p124_2_1" int2,
"p124_2_2" int2,
"p124_2_3" int2,
"p125_1" int2,
"p125_1_1" int2,
"p125_1_2" int2,
"p125_1_3" int2,
"p125_2_1" int2,
"p125_2_2" int2,
"p125_2_3" int2,
"p126" int2,
"p127_1" int2,
"p127_2" varchar(25) DEFAULT NULL::character varying,
"p127_3" varchar(25) DEFAULT NULL::character varying,
"p127_4" int2,
"p127_5" varchar(30) DEFAULT NULL::character varying,
"p127_6" varchar(30) DEFAULT NULL::character varying,
"p128_1" int2,
"p128_2" varchar(30) DEFAULT NULL::character varying,
"p128_3" varchar(30) DEFAULT NULL::character varying,
"p128_4" varchar(30) DEFAULT NULL::character varying,
"p129_1_1" int2,
"p129_1_2" int2,
"p129_1_3" int2,
"p129_1_4" int2,
"p129_1_5" int2,
"p129_1_6" int2,
"p129_2_1" int2,
"p129_2_2" int2,
"p129_2_3" int2,
"p129_2_4" int2,
"p129_2_5" int2,
"p129_2_6" int2,
"p129_3_1" int2,
"p129_3_2" int2,
"p129_3_3" int2,
"p129_3_4" int2,
"p129_3_5" int2,
"p129_3_6" int2,
"p129_4_1" int2,
"p129_4_2" int2,
"p129_4_3" int2,
"p129_4_4" int2,
"p129_4_5" int2,
"p129_4_6" int2,
"p129_5_1" int2,
"p129_5_2" int2,
"p129_5_3" int2,
"p129_5_4" int2,
"p129_5_5" int2,
"p129_5_6" int2,
"p129_6_1" int2,
"p129_6_2" int2,
"p129_6_3" int2,
"p129_6_4" int2,
"p129_6_5" int2,
"p129_6_6" int2,
"p129_7_1" int2,
"p129_7_2" int2,
"p129_7_3" int2,
"p129_7_4" int2,
"p129_7_5" int2,
"p129_7_6" int2,
"p129_8_1" int2,
"p129_8_2" int2,
"p129_8_3" int2,
"p129_8_4" int2,
"p129_8_5" int2,
"p129_8_6" int2,
"p129_9_1" int2,
"p129_9_2" int2,
"p129_9_3" int2,
"p129_9_4" int2,
"p129_9_5" int2,
"p129_9_6" int2,
"p129_10_1" int2,
"p129_10_2" int2,
"p129_10_3" int2,
"p129_10_4" int2,
"p129_10_5" int2,
"p129_10_6" int2,
"p130" int2,
"p131_1_1" varchar(15) DEFAULT NULL::character varying,
"p131_1_2" varchar(2) DEFAULT NULL::character varying,
"p131_1_3" int2,
"p131_1_4" varchar(20) DEFAULT NULL::character varying,
"p131_1_5" numeric(5,2) DEFAULT NULL::numeric,
"p131_1_6" varchar(20) DEFAULT NULL::character varying,
"p131_2_1" varchar(15) DEFAULT NULL::character varying,
"p131_2_2" varchar(2) DEFAULT NULL::character varying,
"p131_2_3" int2,
"p131_2_4" varchar(20) DEFAULT NULL::character varying,
"p131_2_5" numeric(5,2) DEFAULT NULL::numeric,
"p131_2_6" varchar(20) DEFAULT NULL::character varying,
"p131_3_1" varchar(15) DEFAULT NULL::character varying,
"p131_3_2" varchar(2) DEFAULT NULL::character varying,
"p131_3_3" int2,
"p131_3_4" varchar(20) DEFAULT NULL::character varying,
"p131_3_5" numeric(5,2) DEFAULT NULL::numeric,
"p131_3_6" varchar(20) DEFAULT NULL::character varying,
"p131_4_1" varchar(15) DEFAULT NULL::character varying,
"p131_4_2" varchar(2) DEFAULT NULL::character varying,
"p131_4_3" int2,
"p131_4_4" varchar(20) DEFAULT NULL::character varying,
"p131_4_5" numeric(5,2) DEFAULT NULL::numeric,
"p131_4_6" varchar(20) DEFAULT NULL::character varying,
"p131_5_1" varchar(15) DEFAULT NULL::character varying,
"p131_5_2" varchar(2) DEFAULT NULL::character varying,
"p131_5_3" int2,
"p131_5_4" varchar(20) DEFAULT NULL::character varying,
"p131_5_5" numeric(5,2) DEFAULT NULL::numeric,
"p131_5_6" varchar(20) DEFAULT NULL::character varying,
"p132" int2,
"informantecalificado" varchar(80) DEFAULT NULL::character varying,
"dia" varchar(2) DEFAULT NULL::character varying,
"mes" varchar(2) DEFAULT NULL::character varying,
"anio" varchar(4) DEFAULT NULL::character varying,
"observaciones" varchar(800) DEFAULT NULL::character varying,
"estado" varchar(5) DEFAULT NULL::character varying,
"fecharegistro" timestamp(6),
"usuarioregistro" varchar(15) DEFAULT NULL::character varying,
"ipregistro" varchar(20) DEFAULT NULL::character varying,
"fechamodificacion" timestamp(6),
"usuariomodificacion" varchar(15) DEFAULT NULL::character varying,
"ipmodificacion" varchar(20) DEFAULT NULL::character varying,
"tipoaplicacion" varchar(5) DEFAULT NULL::character varying,
"foliocomunal" varchar(6)
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of t_boletaproductor_p2
-- ----------------------------
INSERT INTO "public"."t_boletaproductor_p2" VALUES ('<br/>', '000001', '01', '1', '1', '1234', '01', '01', '01', '01', '01', '1', '11', 'SU', 'MANTA', '12', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', 'WERQ', '12', '1', '1SDFSFA', '12.00', '12', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-04 16:30:26.348189', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p2" VALUES ('<br/>', '000002', '01', '1', '1', '1233', '01', '01', '01', '01', '01', '1', '11', 'SU', 'DEBUGADO', '01', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'INFORMANTE DEBUG', '12', '11', '2013', null, '1', '2013-12-04 16:43:55.546412', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p2" VALUES ('<br/>', '000003', '01', '1', '1', '1231', '01', '01', '01', '01', '01', '1', '11', 'SU', 'DEBUG 2', '12', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-04 17:00:46.056177', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p2" VALUES ('', '000004', '01', '4', '4', '4444', '01', '01', '01', '01', '01', '1', '11', 'SU', 'DEBUG 4', '02', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-04 17:11:37.859719', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p2" VALUES ('', '000005', '01', '', '', '', '01', '01', '01', '01', '01', '1', '11', 'su', '', '', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-04 17:25:49.642718', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p2" VALUES ('', '000006', '01', '', '', '', '01', '01', '01', '01', '01', '1', '11', 'SU', '', '', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-04 18:05:23.638094', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p2" VALUES ('', '000007', '11', '', '', '', '01', '01', '01', '01', '01', '1', '01', 'SUC', '', '', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'DEBUG', '12', '11', '2013', null, '1', '2013-12-04 18:22:55.234106', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p2" VALUES ('', '000123', '01', '1', '1', '1231', '01', '01', '01', '01', '01', '1', '1', 'COMUNIDAD SUCRE', 'PRUEBA', '12', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-03 11:11:36.255048', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p2" VALUES ('', '000321', '11', '1', '1', '1233', '01', '01', '01', '01', '01', '1', '01', 'SUC', 'OEIWRU', '12', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', 'QWE', '12', '1', 'ADADSA', '12.00', '12', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', 'CALIFICADO', '12', '11', '2013', null, '1', '2013-12-04 16:00:43.72266', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p2" VALUES ('', '000456', '01', '1', '1', '1321', '01', '01', '01', '02', '01', '1', '02', 'DOS TRES', 'CUATRO', '12', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', '2013-12-03 16:19:51.868061', 'prueba-trans', '127.0.0.1', null, null, null, null, null);
INSERT INTO "public"."t_boletaproductor_p2" VALUES ('', '000789', '01', '1', '1', '1234', '01', '01', '01', '02', '01', '1', '02', 'DOS TRES', 'CUATRO', '12', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', 'GANGOCHO', '12', '1', 'PAPA', '12.00', '12', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '1', 'JUAN DEL MONTE', '02', '11', '2013', null, '1', '2013-12-04 10:34:10.292259', 'prueba-trans', '127.0.0.1', null, null, null, null, null);

-- ----------------------------
-- Alter Sequences Owned By 
-- ----------------------------

-- ----------------------------
-- Indexes structure for table t_boletaproductor_p2
-- ----------------------------
CREATE INDEX "t_boletaproductor_p2_docid_idx" ON "public"."t_boletaproductor_p2" USING btree ("docid");

-- ----------------------------
-- Primary Key structure for table "public"."t_boletaproductor_p2"
-- ----------------------------
ALTER TABLE "public"."t_boletaproductor_p2" ADD PRIMARY KEY ("folio");
